/*
 Copyright 2012 Stefan Ganzer

 This file is part of QRCodeGen.

 QRCodeGen is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 QRCodeGen is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package qrcodegen.modules.vcardgenpanel.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.charset.Charset;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.DocumentListener;
import javax.swing.text.DocumentFilter;
import qrcodegen.documentfilter.DocumentEncodableFilter;
import qrcodegen.documentfilter.DocumentSizeFilter;
import qrcodegen.tools.SwingTools;

/**
 *
 * @author Stefan Ganzer
 */
public final class EMailPanel extends javax.swing.JPanel {

	public static final String EMAIL_FIELD = "EMail";
	public static final String OTHER_PARAMETER = "Other";
	public static final String WORK_PARAMETER = "Work";
	public static final String HOME_PARAMETER = "Home";
	private static final ResourceBundle RES = ResourceBundle.getBundle("qrcodegen/modules/vcardgenpanel/view/EMailPanel");
	private static final DocumentFilter FILTER = new DocumentSizeFilter(100, new DocumentEncodableFilter(Charset.forName("UTF-8")));

	/** Creates new form VCardNamePanel */
	public EMailPanel() {
		initComponents();
		initFilter();
		initWorkHomeSelectorActionListener();
		initEMailField();
	}

	private void initFilter() {
		SwingTools.setDocumentFilter(eMailField, FILTER);
	}

	public String getEMail() {
		return eMailField.getText();
	}

	public void setEMail(String value) {
		if (!eMailField.getText().equals(value)) {
			eMailField.setText(value);
		}
	}

	public void setOtherSelected(boolean selected) {
		workHomeSelector.otherRadioButtonSetSelected(selected);
	}

	public boolean isOtherSelected() {
		return workHomeSelector.isOtherRadioButtonSelected();
	}

	public void setHomeSelected(boolean selected) {
		workHomeSelector.homeRadioButtonSetSelected(selected);
	}

	public boolean isHomeSelected() {
		return workHomeSelector.isHomeRadioButtonSelected();
	}

	public void setWorkSelected(boolean selected) {
		workHomeSelector.workRadioButtonSetSelected(selected);
	}

	public boolean isWorkSelected() {
		return workHomeSelector.isWorkRadioButtonSelected();
	}

	private void initEMailField() {
		DocumentListener listener = new UpdateableDocumentListener(new Updateable() {
			@Override
			public void updateField() {
				//presentationModel.setNumber(telephoneField.getText());
				firePropertyChange(EMAIL_FIELD, null, null);
			}
		});
		eMailField.getDocument().addDocumentListener(listener);
	}

	private void initWorkHomeSelectorActionListener() {
		final ActionListener al = new ButtonListener();
		workHomeSelector.otherRadioButtonAddActionListener(al);
		workHomeSelector.homeRadioButtonAddActionListener(al);
		workHomeSelector.workRadioButtonAddActionListener(al);
	}

	private class ButtonListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			final String actionCommand = e.getActionCommand();
			if (WorkHomeSelector2.OTHER_ACTION_COMMAND.equals(actionCommand)) {
				firePropertyChange(OTHER_PARAMETER, null, null);
			} else if (WorkHomeSelector2.HOME_ACTION_COMMAND.equals(actionCommand)) {
				firePropertyChange(HOME_PARAMETER, null, null);
			} else if (WorkHomeSelector2.WORK_ACTION_COMMAND.equals(actionCommand)) {
				firePropertyChange(WORK_PARAMETER, null, null);
			}
		}
	}

	/** This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eMailLabel = new JLabel();
        eMailField = new JTextField();
        workHomeSelector = new WorkHomeSelector2();

        eMailLabel.setText(RES.getString("EMailPanel.eMailLabel.text_1")); // NOI18N

        eMailField.setColumns(15);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eMailLabel)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(eMailField)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(workHomeSelector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.CENTER)
                    .addComponent(eMailLabel)
                    .addComponent(eMailField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(workHomeSelector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField eMailField;
    private JLabel eMailLabel;
    private WorkHomeSelector2 workHomeSelector;
    // End of variables declaration//GEN-END:variables
}