/*
 Copyright 2011, 2012 Stefan Ganzer
 
 This file is part of QRCodeGen.

 QRCodeGen is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 QRCodeGen is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * $Revision: 1162 $
 */
package qrcodegen;

import qrcodegen.tools.SwingTools;

import javax.swing.*;
import java.util.ResourceBundle;

/**
 *
 * @author Stefan Ganzer
 */
public class AboutDialog extends javax.swing.JDialog {

	/** The resourse bundle for this class AboutDialog */
	private static final ResourceBundle res = ResourceBundle.getBundle("qrcodegen/AboutDialog");
	private static final String SUBJECT = null; //NOI18N
	private static final String ADDRESS = "Stefan%20Ganzer%20%3Cportableqrcodegenerator@gmail.com%3E"; //NOI18N
	private final String eMailBody;

	/** Creates new form AboutDialog */
	public AboutDialog(java.awt.Frame parent, boolean modal, String version) {
		super(parent, modal);
		if (version == null) {
			throw new NullPointerException();
		}
		this.eMailBody = "Version:%20" + version;
		initComponents();
		versionField.setText("v. " + version);
		SwingTools.registerEscKeyForClosing(this);

		if (Linkify.isBrowsingSupported()) {
			//Modify JLabels that contain a http-link in such a way that
			//clicking on the link opens it in the default browser
			Linkify.makeHTTPLinkable(linkLabel);
			Linkify.makeHTTPLinkable(zxingLinkLabel);
			Linkify.makeMailLinkable(emailLabel, ADDRESS, SUBJECT, eMailBody);
		}
	}

	/** This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        zxingLinkLabel = new javax.swing.JLabel();
        linkLabel = new javax.swing.JLabel();
        license1Label = new javax.swing.JLabel();
        license2Label = new javax.swing.JLabel();
        license3Label = new javax.swing.JLabel();
        license4Label = new javax.swing.JLabel();
        zxing1Label = new javax.swing.JLabel();
        zxing2Label = new javax.swing.JLabel();
        zxing3Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        denso1Label = new javax.swing.JLabel();
        denso2Label = new javax.swing.JLabel();
        versionField = new javax.swing.JTextField();
        zxing4Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(res.getString("ABOUT")); // NOI18N

        jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headingLabel.setText("Portable QR-Code Generator");

        copyrightLabel.setText("<html> &copy; 2011, 2012, 2013 by Stefan Ganzer</html>");

        zxingLinkLabel.setText("https://code.google.com/p/zxing/");

        linkLabel.setText("https://sites.google.com/site/qrcodeforwn/");
        linkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        license1Label.setText(res.getString("AboutDialog.license1Label.text")); // NOI18N

        license2Label.setText(res.getString("AboutDialog.license2Label.text")); // NOI18N

        license3Label.setText(res.getString("AboutDialog.license3Label.text")); // NOI18N

        license4Label.setText(res.getString("AboutDialog.license4Label.text")); // NOI18N

        zxing1Label.setText(res.getString("AboutDialog.zxing1Label.text")); // NOI18N

        zxing2Label.setText(res.getString("AboutDialog.zxing2Label.text")); // NOI18N

        zxing3Label.setText(res.getString("AboutDialog.zxing3Label.text")); // NOI18N

        jLabel1.setText(res.getString("AboutDialog.jLabel1.text")); // NOI18N

        denso1Label.setText(res.getString("AboutDialog.denso1Label.text")); // NOI18N

        denso2Label.setText(res.getString("AboutDialog.denso2Label.text")); // NOI18N

        versionField.setEditable(false);
        versionField.setText(res.getString("AboutDialog.versionField.text")); // NOI18N
        versionField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        zxing4Label.setText(res.getString("AboutDialog.zxing4Label.text")); // NOI18N

        emailLabel.setText(res.getString("AboutDialog.emailLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(headingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(copyrightLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linkLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(license1Label)
                    .addComponent(license2Label)
                    .addComponent(license3Label)
                    .addComponent(license4Label)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zxing1Label)
                    .addComponent(zxing2Label)
                    .addComponent(zxing3Label)
                    .addComponent(zxingLinkLabel)
                    .addComponent(denso1Label)
                    .addComponent(denso2Label)
                    .addComponent(zxing4Label)
                    .addComponent(emailLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLabel)
                    .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel)
                .addGap(18, 18, 18)
                .addComponent(license1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(license2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(license3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(license4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zxing1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zxing2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zxing3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zxing4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zxingLinkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denso1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denso2Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setMnemonic('O');
        okButton.setText(res.getString("AboutDialog.okButton.text")); // NOI18N
        okButton.addActionListener(evt -> okButtonActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed() {//GEN-FIRST:event_okButtonActionPerformed
		dispose();
	}//GEN-LAST:event_okButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException ex) {
			java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(() -> {
            AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true, "test");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel denso1Label;
    private javax.swing.JLabel denso2Label;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel license1Label;
    private javax.swing.JLabel license2Label;
    private javax.swing.JLabel license3Label;
    private javax.swing.JLabel license4Label;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField versionField;
    private javax.swing.JLabel zxing1Label;
    private javax.swing.JLabel zxing2Label;
    private javax.swing.JLabel zxing3Label;
    private javax.swing.JLabel zxing4Label;
    private javax.swing.JLabel zxingLinkLabel;
    // End of variables declaration//GEN-END:variables
}
