/*
 Copyright 2012 Stefan Ganzer

 This file is part of QRCodeGen.

 QRCodeGen is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 QRCodeGen is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package qrcodegen.modules;

import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.util.ResourceBundle;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Stefan Ganzer
 */
public class AsciiHexSelector extends javax.swing.JPanel {

	public static final String ASCII_ACTION_COMMAND = "ASCII";
	public static final String HEX_ACTION_COMMAND = "HEX";
	private static final ResourceBundle RES = ResourceBundle.getBundle("qrcodegen/modules/AsciiHexSelector");

	/** Creates new form AsciiHexSelector */
	public AsciiHexSelector() {
		initComponents();
	}

	public void setLabel(String value) {
		label.setText(value);
	}

	public String getLabel() {
		return label.getText();
	}

	public void setToolTipTextAsciiButton(String value) {
		asciiButton.setToolTipText(value);
	}

	public void setToolTipTextHexButton(String value) {
		hexButton.setToolTipText(value);
	}

	public void addActionListener(ActionListener listener) {
		asciiButton.addActionListener(listener);
		hexButton.addActionListener(listener);
	}

	@Override
	public void setEnabled(boolean enabled) {
		super.setEnabled(enabled);
		asciiButton.setEnabled(enabled);
		hexButton.setEnabled(enabled);
	}

	/** This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        asciiButton = new JRadioButton();
        hexButton = new JRadioButton();
        label = new JLabel();

        buttonGroup1.add(asciiButton);
        asciiButton.setSelected(true);
        asciiButton.setText(MessageFormat.format(RES.getString("AsciiHexSelector.asciiButton.text"), new Object[] {})); // NOI18N
        asciiButton.setActionCommand(ASCII_ACTION_COMMAND);

        buttonGroup1.add(hexButton);
        hexButton.setText(MessageFormat.format(RES.getString("AsciiHexSelector.hexButton.text"), new Object[] {})); // NOI18N
        hexButton.setActionCommand(HEX_ACTION_COMMAND);

        label.setText(MessageFormat.format(RES.getString("AsciiHexSelector.label.text"), new Object[] {})); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(asciiButton)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(hexButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(asciiButton)
                    .addComponent(hexButton)
                    .addComponent(label))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JRadioButton asciiButton;
    private ButtonGroup buttonGroup1;
    private JRadioButton hexButton;
    private JLabel label;
    // End of variables declaration//GEN-END:variables
}
